/**
 * data/revision.ts - GENERATED by scripts/write-revision.js. Do not edit.
 * The revision advances only when data/models.ts, data/companies.ts or
 * data/leaderboard.ts content changes. Consumers must treat revisedAt as the
 * dataset's last real change, never as a build timestamp.
 */
export const datasetRevision = {
  datasetVersion: "2026.10.08",
  revisedAt: "2026-10-08",
  contentHash: "2b95f3b13b6ffb14",
  sourceAudit: "docs/audit-2026-10-07.md",
} as const
