#!/usr/bin/env node

/**
 * scripts/sync-readme.js
 * Automatically synchronizes the frontier models table in README.md from data/models.ts.
 * Ensures contributors only ever need to edit data/models.ts.
 */

const fs = require("fs")
const path = require("path")
const ts = require("typescript")
const vm = require("vm")

function loadTsModule(relPath) {
  const fullPath = path.resolve(__dirname, relPath)
  const source = fs.readFileSync(fullPath, "utf8")
  const transpiled = ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 },
  }).outputText

  const mod = { exports: {} }
  const ctx = vm.createContext({
    module: mod,
    exports: mod.exports,
    require,
    console,
  })
  vm.runInContext(transpiled, ctx)
  return mod.exports
}

const { modelsData } = loadTsModule("../data/models.ts")
const { companies } = loadTsModule("../data/companies.ts")

function formatContext(tokens) {
  if (tokens >= 1000000) {
    const val = tokens / 1000000
    if (Math.abs(val - 1.048576) < 0.06 || Math.abs(val - 1) < 0.01) return "1M"
    return `${val.toFixed(2).replace(/\.?0+$/, "")}M`
  }
  if (tokens >= 1000) {
    const thousands = Math.round(tokens / 1000)
    return `${thousands}k`
  }
  return String(tokens)
}

function formatPricing(model) {
  if (model.openWeights && model.pricing.input === 0) {
    return "Free (Open)"
  }
  return `$${model.pricing.input} in / $${model.pricing.output} out`
}

function generateMarkdownTable() {
  const companyKeys = Object.keys(companies)

  const rows = companyKeys.map((companyId) => {
    const company = companies[companyId]
    const flagship = modelsData.find((m) => m.companyId === companyId && m.isCompanyFlagship)
    const latestDrop = modelsData.find(
      (m) => m.companyId === companyId && m.isLatestCheckpoint && m.id !== flagship?.id
    )

    const flagshipCell = flagship
      ? `[${flagship.name}](https://modelregistry.tirup.in/models/${flagship.id})`
      : "—"

    const latestDropCell = latestDrop
      ? `[${latestDrop.name}](https://modelregistry.tirup.in/models/${latestDrop.id})`
      : "—"

    const contextCell = flagship ? formatContext(flagship.contextWindowTokens) : "—"
    const licenseCell = flagship?.openWeights
      ? `Open (${flagship.license.replace(/ License| \/ .*$/g, "")})`
      : "Proprietary"
    const pricingCell = flagship ? formatPricing(flagship) : "—"

    return `| [**${company.name}**](${company.website}) | ${flagshipCell} | ${latestDropCell} | ${contextCell} | ${licenseCell} | ${pricingCell} |`
  })

  const header = [
    "| Laboratory | Primary Flagship | Latest Checkpoint | Context | Access | Pricing (1M) |",
    "|:---|:---|:---|:---|:---|:---|",
  ]

  return [...header, ...rows].join("\n")
}

function syncReadme(checkOnly = false) {
  const readmePath = path.resolve(__dirname, "../README.md")
  const readmeContent = fs.readFileSync(readmePath, "utf8")

  const startMarker = "<!-- REGISTRY_TABLE_START -->"
  const endMarker = "<!-- REGISTRY_TABLE_END -->"

  const startIndex = readmeContent.indexOf(startMarker)
  const endIndex = readmeContent.indexOf(endMarker)

  if (startIndex === -1 || endIndex === -1) {
    console.error("❌ Could not find <!-- REGISTRY_TABLE_START --> and <!-- REGISTRY_TABLE_END --> markers in README.md")
    process.exit(1)
  }

  const tableMarkdown = generateMarkdownTable()
  const newSection = `${startMarker}\n<!-- Auto-generated by scripts/sync-readme.js - Do not edit manually -->\n${tableMarkdown}\n`

  const updatedReadme = readmeContent.slice(0, startIndex) + newSection + readmeContent.slice(endIndex)

  if (checkOnly) {
    if (readmeContent !== updatedReadme) {
      console.error("❌ README.md frontier models table is out of date! Run: node scripts/sync-readme.js")
      process.exit(1)
    } else {
      console.log("✔ README.md frontier models table is up to date.")
      process.exit(0)
    }
  }

  if (readmeContent !== updatedReadme) {
    fs.writeFileSync(readmePath, updatedReadme, "utf8")
    console.log("✔ Successfully synchronized README.md frontier models table.")
  } else {
    console.log("✔ README.md is already up to date with data/models.ts.")
  }
}

const checkOnly = process.argv.includes("--check")
syncReadme(checkOnly)
